ROOT/GSL integrator
pawelsznajder/epic pull request #25
Opened 2024-02-23 13:24 UTC by forthommel

This PR introduces a new "event_generator" module implementation, based on ROOT's [Math::IntegratorMultiDim](https://root.cern.ch/doc/master/classROOT_1_1Math_1_1IntegratorMultiDim.html).

It allows to compute cross sections in a more numerically stable ways than the usual Foam method, thanks in particular to ROOT's C++ wrappers to GSL's Vegas, Miser, and plain [Monte Carlo integrator algorithms](https://www.gnu.org/software/gsl/doc/html/montecarlo.html) implementations.

This results in shorter runs for most algorithms used, and comparable or better precisions reached for a same run time. For instance, running the [epic_scenario_DVCS.xml](https://github.com/pawelsznajder/epic/blob/main/data/examples/epic_scenario_DVCS.xml) example on an 8th Gen Intel CORE i7 vPro with 16 Gb RAM:

- Foam (with 100k events generation upstream, 22'45" run):
  ```
  Integrated cross-section (value) [nb]: 4.745535713297
  Integrated cross-section (uncertainty) [nb]: 0.0190818197995742
  ```
- Miser (no event generation, 1'38" run):
  ```
  Integrated cross-section (value) [nb]: 4.71182617972158
  Integrated cross-section (uncertainty) [nb]: 0.0555660423376965
  ```
- Vegas (no event generation, '" run):
  ```
  Integrated cross-section (value) [nb]: 4.74743323842268
  Integrated cross-section (uncertainty) [nb]: 0.00602654005686526
  ```

2024-02-25 16:02 UTC, JJJhonzon requested changes
**de**

2024-03-13 16:32 UTC, forthommel commented
Hello @pawelsznajder.
In this last commit a35715e, we try to minimalise the changes in the EPiC workflow by computing the cross section at the initialisation stage, instead of the end of the run.
The PR is now ready for your review!

FYI: @hamzeh-khanpour

2024-03-13 16:51 UTC, pawelsznajder approved these changes

2024-03-13 16:51 UTC, merged

2024-03-13 16:58 UTC, pawelsznajder commented
I would not call it very fast ;) I totally forgot to make the merge after our last discussion, sorry for that. Anyway, the new release (including your changes) should be ready in few minutes.